name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Extract version
        id: vars
        run: |
          GIT_MESSAGE="${{ github.event.commits[0].message }}"
          VERSION=$(echo "$GIT_MESSAGE" | sed -e 's/[Rr]evert "//g' -e 's/"//g' | cut -d'|' -f1 | xargs)
          [ -z "$VERSION" ] && VERSION="latest"
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend_react
          push: true
          tags: |
            michelm2306/list-frontend:${{ env.APP_VERSION }}
            michelm2306/list-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./spring_backend
          push: true
          tags: |
            michelm2306/list-backend:${{ env.APP_VERSION }}
            michelm2306/list-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  backend-integration-tests:
    name: Run postman collection
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Start Backend
        run: |
          docker compose -f frontend_react/docker-compose.yml pull
          docker compose -f frontend_react/docker-compose.yml up -d
          sleep 10
      - name: Install and Run Newman
        working-directory: ./spring_backend/postman
        run: |
          COLLECTION=$(find ./collections -name "*postman_collection.json" | head -n 1)
          ENVIRONMENT=$(find . -maxdepth 1 -name "*Environment.postman_environment.json" | head -n 1)
          npx newman run "$COLLECTION" ${ENVIRONMENT:+-e "$ENVIRONMENT"} --env-var "baseUrl=http://localhost:8923" --reporters cli
      - name: Stop and cleanup Docker
        if: always()
        run: docker compose -f frontend_react/docker-compose.yml down

  frontend-e2e-tests:
    runs-on: ubuntu-latest
    needs: backend-integration-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Compose
        run: docker compose -f frontend_react/docker-compose.yml up -d
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend_react
          cache-key: ${{ runner.os }}-cypress-${{ hashFiles('frontend_react/package-lock.json') }}
          wait-on: 'http://localhost:8922'
          wait-on-timeout: 120
          config: baseUrl=http://localhost:8922
      - name: Stop containers
        if: always()
        run: docker compose -f frontend_react/docker-compose.yml down

  deploy:
    runs-on: ubuntu-latest
    needs: frontend-e2e-tests
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          script: |
            cd ~/UEK-223-Group-6-Frontend/frontend_react
            git pull origin main
            docker compose pull
            docker compose up -d --force-recreate
            pkill ngrok || true
            nohup ngrok http --url michel.dev.noseryoung.com 8923 > ngrok.log 2>&1 &

  health-check:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Remote Health Check
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          script: |
            sleep 20
            curl -fskL https://michel.dev.noseryoung.ch || exit 1

  message-success:
    runs-on: ubuntu-latest
    needs: health-check
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v7.0.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        content: "✅ Michel submitted a new commit. [visit site](https://michel.dev.noseryoung.ch) #StayComitting #AuraFarming"
        embed-image-url: "https://cdn.dailysports.net/dailysports/20250914/63ee67a9f021b7766460a42ba6f6b5f7dd1b299c7bc31df0c17b9429f8f37ca3-1200-675.jpg"
        embed-title: "Aura"
        embed-color: "0x00ff00"

  revert-commit:
    runs-on: ubuntu-latest
    needs: [build, backend-integration-tests, frontend-e2e-tests, deploy, health-check]
    if: always() && contains(needs.*.result, 'failure')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - name: Revert last commit
        run: |
          git config --global user.name "mm2306"
          git config --global user.email "michel.mahadeva@edu.tbz.ch"
          git revert HEAD --no-edit
          git push origin main
      - name: Discord Failure Message
        if: always()
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "⚠️ **Pipeline Failed!** Reverting last commit. Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-image-url: "https://static01.nyt.com/athletic/uploads/wp/2026/01/18164722/GettyImages-2256403929.jpg"
          embed-color: 16711680
          embed-title: "Aura loss"